### ISSUE TITLE
移动到不同元素上显示不同消息怎么弄

### ISSUE THREAD

**Issue by Oct1a** [214L/leafer-x-popup-canvas#1]
看文档好像只能传入app跟Leafer，如果我传图形元素的话，是直接报错

**Comment by 214L** [comment]
传入的app和Leafer是用来确定渲染的“根元素”的。

如果想显示/不显示某些元素，可以使用includesType或者excludesType配置。
```
new TooltipPlugin(app, {
  info: ['width', 'height', 'innerId'],
  includesType: ['Rect'],
  excludesType: [],
  ...
})
```
如果想根据元素的不同类型显示不同的字段，可以在formatter配置中返回不同字符串实现
```js
formatter: (item) => {
    return `${item.tag}(${item.innerId})`
}
```

**Comment by 214L** [comment]
> 看文档好像只能传入app跟Leafer，如果我传图形元素的话，是直接报错

@Oct1a 

传入的app和Leafer是用来确定渲染的“根元素”的。

如果想显示/不显示某些元素，可以使用includesType或者excludesType配置。
```
new TooltipPlugin(app, {
  info: ['width', 'height', 'innerId'],
  includesType: ['Rect'],
  excludesType: [],
  ...
})
```
如果想根据元素的不同类型显示不同的字段，可以在formatter配置中返回不同字符串实现
```js
formatter: (item) => {
    return `${item.tag}(${item.innerId})`
}
```

**Comment by Oct1a** [comment]
好的，感谢！
