### ISSUE TITLE
支持自定义元素？

### ISSUE THREAD

**Issue by hiifong** [214L/leafer-x-popup-canvas#2]

**Comment by 214L** [comment]
> _No description provided._
@hiifong 

支持自定义元素，`includesType`字段传入自定义元素的Tag即可。

**Comment by hiifong** [comment]
> > _No description provided._
> > @hiifong
> 
> 支持自定义元素，`includesType`字段传入自定义元素的Tag即可。

我是用flow布局，往里面添加自定义元素，`includesType`也加入自定义元素了，发现这个插件只显示flow的

**Comment by 214L** [comment]
> > > _No description provided._
> > > @hiifong
> > 
> > 
> > 支持自定义元素，`includesType`字段传入自定义元素的Tag即可。
> 
> 我是用flow布局，往里面添加自定义元素，`includesType`也加入自定义元素了，发现这个插件只显示flow的

我复现修复一下，感谢反馈。

**Comment by 214L** [comment]
@hiifong 问题已在v1.0.1版本修复，可以更新版本以解决问题。

**Comment by hiifong** [comment]
> @hiifong 问题已在v1.0.1版本修复，可以更新版本以解决问题。

OK
